version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization
      - indices.query.bool.max_clause_count=1024
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  code:
    container_name: "elasticsearch_elixir"
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated
    environment:
      - "DATABASE_HOST=db"
      - "ELASTICSEARCH_HOST=elasticsearch"
    depends_on:
      - db
      - elasticsearch
    links:
      - db:postgres

volumes:
  esdata:
